/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gc.presentation;

import gc.dao.PrestataireDAO;
import gc.entities.Prestataire;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;

/**
 *
 * @author Cyrine
 */
public class Afficher_prestataire extends javax.swing.JFrame {

    /**
     * Creates new form Afficher_prestataire
     */
    String s="";

    public Afficher_prestataire() {
       
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
         
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
       // Table_pres.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
  
       JTableHeader header = Table_pres.getTableHeader();
   TableColumn column =  Table_pres.getColumnModel().getColumn(0);
   header.setResizingColumn(column);            // this line is very important
   column.setMinWidth(0);           // permettre une largeur zéro
   column.setWidth(0);
   
    //column.setCellEditor(null);
   
   
    }
    public Afficher_prestataire(String s) {
       
        this.s=s;
        initComponents();
       
        Table_pres.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
   JTableHeader header = Table_pres.getTableHeader();
   TableColumn column =  Table_pres.getColumnModel().getColumn(0);
   header.setResizingColumn(column);            // this line is very important
   column.setMinWidth(0);           // permettre une largeur zéro
   column.setWidth(0);
   
  
        
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
         //this.pack();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Table_pres = new javax.swing.JTable();
        btnAjouter = new javax.swing.JButton();
        btnSupprimer = new javax.swing.JButton();
        tfChampRecherche = new javax.swing.JTextField();
        btnRechercher = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnPlusDeDetails = new javax.swing.JButton();
        btnModifier = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(620, 380));
        setResizable(false);
        getContentPane().setLayout(null);

        Table_pres.setModel(new AfficherPrestataire(s));
        jScrollPane1.setViewportView(Table_pres);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 110, 590, 150);

        btnAjouter.setText("Ajouter");
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });
        getContentPane().add(btnAjouter);
        btnAjouter.setBounds(50, 290, 100, 23);

        btnSupprimer.setText("Supprimer");
        btnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerActionPerformed(evt);
            }
        });
        getContentPane().add(btnSupprimer);
        btnSupprimer.setBounds(320, 290, 110, 23);
        getContentPane().add(tfChampRecherche);
        tfChampRecherche.setBounds(130, 70, 320, 30);

        btnRechercher.setText("Rechercher");
        btnRechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRechercherActionPerformed(evt);
            }
        });
        getContentPane().add(btnRechercher);
        btnRechercher.setBounds(473, 70, 130, 30);

        jLabel2.setText("Nom du prestataire:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 70, 140, 30);

        btnPlusDeDetails.setText("Plus de details..");
        btnPlusDeDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusDeDetailsActionPerformed(evt);
            }
        });
        getContentPane().add(btnPlusDeDetails);
        btnPlusDeDetails.setBounds(460, 290, 150, 23);

        btnModifier.setText("modifier");
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });
        getContentPane().add(btnModifier);
        btnModifier.setBounds(190, 290, 100, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Liste des prestataires");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(200, 20, 270, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gc/presentation/1801091_595630270513775_1127831772_n.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 650, 336);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
        // TODO add your handling code here:
        Ajout_prestataire ajout_prestataire = new Ajout_prestataire();
        //this.setVisible(false);
        this.dispose();
        ajout_prestataire.setVisible(true);
    }//GEN-LAST:event_btnAjouterActionPerformed

    private void actualiser()
    {
        Afficher_prestataire p_nv =new Afficher_prestataire();
        this.setVisible(false);
        p_nv.setVisible(true);
        
    }
    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerActionPerformed
        // TODO add your handling code here:
        if(Table_pres.getSelectedRow()<0)
        {
             JOptionPane.showMessageDialog(null,"Selectionnez un prestataire pour le supprimer");
        }
        else
        {
        
        int ligne_selectionee=Table_pres.getSelectedRow();
        
          int id = (int) Table_pres.getValueAt(ligne_selectionee, 0);
          //System.out.println(id);
          PrestataireDAO pDAO =new PrestataireDAO();
          pDAO.deletePrestataire(id);
          
          this.actualiser();
          
        }   
    }//GEN-LAST:event_btnSupprimerActionPerformed

    private void btnRechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechercherActionPerformed

        // TODO add your handling code here:
      s=tfChampRecherche.getText();
    
      
      AfficherPrestataire mod=new AfficherPrestataire(s);
      Table_pres.setModel(mod);
       
    }//GEN-LAST:event_btnRechercherActionPerformed

    private void btnPlusDeDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusDeDetailsActionPerformed
        // TODO add your handling code here:
        if(Table_pres.getSelectedRow()>=0)
        {
        int ligne_selectionee=Table_pres.getSelectedRow();
          int id = (int) Table_pres.getValueAt(ligne_selectionee, 0);
          Afficher_detail_prestataire detail =new Afficher_detail_prestataire(id,this);
          
          detail.setVisible(true);
          this.setVisible(false);
          
          
        }
        else
        {
             JOptionPane.showMessageDialog(null,"Selectionnez un prestataire pour afficher ses details");
        }
        
    }//GEN-LAST:event_btnPlusDeDetailsActionPerformed

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
        // TODO add your handling code here:
         
          if((Table_pres.getSelectedRow()) >= 0)
          {
              int ligne_selectionee=Table_pres.getSelectedRow();
              int id = (int) Table_pres.getValueAt(ligne_selectionee,0);
            
             PrestataireDAO pdao=new PrestataireDAO();
             Prestataire p = pdao.findPrestataireById(id);
             
             this.dispose();
              modifier_prestataire modif_pres=new modifier_prestataire(id,this);
              modif_pres.setVisible(true);   
          }
          else
          {
                JOptionPane.showMessageDialog(null,"Selectionnez un prestataire pour le modifier");
          }
    }//GEN-LAST:event_btnModifierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Afficher_prestataire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Afficher_prestataire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Afficher_prestataire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Afficher_prestataire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Afficher_prestataire().setVisible(true);
            }
        });
        
       
        
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_pres;
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnPlusDeDetails;
    private javax.swing.JButton btnRechercher;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfChampRecherche;
    // End of variables declaration//GEN-END:variables
}
